server:
  port: 9000

spring:
  application:
    name: story-admin
  profiles:
    include: jdbc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

jwt:
  config:
    token-expire-time: 1
    secret-key: story-admin


