server:
  port: 9000

spring:
  application:
    name: java-vue
  profiles:
    include: jdbc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    password:           #密码（默认为空）
    database: 10        #Redis索引0~15，默认为0


#配置JWT
jwt:
  config:
    token-expire-time: 2 #token的过期时间要长于刷新token时间
    refresh-token-time: 1
    secret-key: java-vue


#配置shiro拦截器链
shiro:
  filter:
    chain:
      perms:
        - path: /
          filter: anon
        - path: /sys/user/login
          filter: anon
        - path: /webjars/**
          filter: anon
        - path: /druid/**
          filter: anon
        - path: /**
          filter: jwt


