server:
  port: 9000

spring:
  application:
    name: java-vue
  profiles:
    include: jdbc
  jackson: #日期返回前端乱码处理
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart: #文件上传大小设置，默认最大 1MB
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  config:
    token-expire-time: 60
    secret-key: java-vue

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI4FrLarzdcXnMzi93gviG
    access-key-secret: 换成自己的
    bucket-name: java-vue
    file-host: avatar
    expire: 300
    max-size: 20

