server:
  port: 9000

spring:
  application:
    name: java-vue
  profiles:
    include: jdbc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379

jwt:
  config:
    token-expire-time: 1
    refresh-check-time: 1
    public-key-path: D:\\rsa\\rsa_key.pub
    private-key-path: D:\\rsa\\rsa_key.pri
    key-secret: java-vue-secret
    key-size: 2048



